// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WifiAPIExam.Database;

#nullable disable

namespace WifiAPIExam.Migrations
{
    [DbContext(typeof(WifiDbContext))]
    partial class WifiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WifiAPIExam.Database.Entities.WifiDataEntity", b =>
                {
                    b.Property<int>("VoucherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VoucherId"));

                    b.Property<string>("ActivationCc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ActivationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Billing")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<string>("CreditCardCountry")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DataReceivedKB")
                        .HasColumnType("integer");

                    b.Property<int>("DataSentKB")
                        .HasColumnType("integer");

                    b.Property<string>("DepartureCc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DestinationCc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Devices")
                        .HasColumnType("integer");

                    b.Property<decimal>("Fees")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PriceNok")
                        .HasColumnType("numeric");

                    b.Property<int>("RefundNok")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RefundTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SellTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ShipId")
                        .HasColumnType("integer");

                    b.Property<int>("TimeQuotaMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("UniqueThisMonth")
                        .HasColumnType("integer");

                    b.Property<int>("UniqueToday")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VatCountry")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VolumeQuotaMB")
                        .HasColumnType("integer");

                    b.HasKey("VoucherId");

                    b.HasIndex("ShipId", "SellTime");

                    b.ToTable("WifiDatabase");
                });

            modelBuilder.Entity("WifiAPIExam.Database.Entities.WifiShipEntity", b =>
                {
                    b.Property<int>("ShipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ShipId"));

                    b.HasKey("ShipId");

                    b.ToTable("ShipIds");
                });
#pragma warning restore 612, 618
        }
    }
}
